# Generated by Django 5.2.14 on 2026-06-29 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Book Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price')),
                ('pages', models.PositiveIntegerField(verbose_name='Pages')),
                ('language', models.CharField(max_length=50, verbose_name='Language')),
                ('isbn', models.CharField(max_length=13, unique=True, verbose_name='ISBN')),
                ('publish_year', models.PositiveIntegerField(verbose_name='Publish Year')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='Stock')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='books/', verbose_name='Cover Image')),
                ('author', models.CharField(max_length=150, verbose_name='Author')),
                ('category', models.CharField(max_length=100, verbose_name='Category')),
                ('publisher', models.CharField(max_length=150, verbose_name='Publisher')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Book',
                'verbose_name_plural': 'Books',
                'ordering': ['-created_at'],
            },
        ),
    ]
